# Generated by Django 4.2.16 on 2024-10-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('course_duration', models.IntegerField(default=0)),
                ('paid_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
