# Generated by Django 4.2.16 on 2024-10-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
