# Generated by Django 4.2.16 on 2024-10-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_courses_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='picture',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
