# Generated by Django 4.2.16 on 2024-10-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_remove_courses_picture_courses_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_image',
        ),
        migrations.AddField(
            model_name='courses',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='paid_fee',
            field=models.IntegerField(default=0),
        ),
    ]
