# Generated by Django 4.2.16 on 2024-10-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_remove_courses_course_name_courses_course_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_nam',
            new_name='course_name',
        ),
    ]
