# Generated by Django 4.2.16 on 2024-11-02 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_rename_course_nam_courses_course_name'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Course_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.courses'),
        ),
    ]
